language: node_js
node_js:
  - 12
os: linux
dist: xenial
branches:
  only:
    - master
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint'
  - 'npm install'
  - 'bower install'
jobs:
  include:
    - stage: test
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: 77fbb2bf-d431-480e-a48f-f20f7ad96367
  app: made-up-world-angular
  on:
    repo: mrWD/made-up-world-angular
