language: node_js
node_js:
  - 12
os: linux
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://t-palmer.github.io/travis-demo/
jobs:
  include:
    - stage: test
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: 77fbb2bf-d431-480e-a48f-f20f7ad96367
  app: made-up-world-angular
  on:
    repo: mrWD/made-up-world-angular
